title: Living Habil
description: That is not dead which can eternal lie
theme: just-the-docs

url: https://jomula.github.io/livinghabil

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
